AddNewDisk:
  MountPoint: /mount/data
  VolumeGroup: hadoopvg
  VolumeName: hadoopvl
  Fs: ext4
downloads:
  eclipse:
    url: http://mirrors.yun-idc.com/eclipse//technology/epp/downloads/release/mars/2/eclipse-jee-mars-2-linux-gtk-x86_64.tar.gz
    extractor: "tar -zxf"
    binFolder: ""
  ant:
    url: http://mirror.bit.edu.cn/apache//ant/binaries/apache-ant-1.9.7-bin.tar.gz
    extractor: "tar -zxf"
    binFolder: bin
  maven:
    url: http://mirror.bit.edu.cn/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    extractor: "tar -zxf"
    binFolder: bin
  hadoopPseudo2.5.2:
    url: https://mirrors.tuna.tsinghua.edu.cn/apache/hadoop/common/hadoop-2.5.2/hadoop-2.5.2.tar.gz
    extractor: "tar -zxf"
  hbase0.98.19:
    url: http://mirror.bit.edu.cn/apache/hbase/0.98.19/hbase-0.98.19-hadoop2-bin.tar.gz
    extractor: "tar -zxf"
    hbase.rootdir: /home/vagrant/hbase
    hbase.zookeeper.property.dataDir: /home/vagrant/zookeeper
BigestDisk: /home
