AddNewDisk:
  MountPoint: /mount/data
  VolumeGroup: hadoopvg
  VolumeName: hadoopvl
  Fs: ext4
downloads:
  eclipse:
    url: http://mirrors.yun-idc.com/eclipse//technology/epp/downloads/release/mars/2/eclipse-jee-mars-2-linux-gtk-x86_64.tar.gz
    extractor: "tar -zxf"
    binFolder: ""
  ant:
    url: http://mirror.bit.edu.cn/apache//ant/binaries/apache-ant-1.9.7-bin.tar.gz
    extractor: "tar -zxf"
    binFolder: bin
BigestDisk: /home
