SolrInstallFolder: /opt/solrapp
SolrDataFolder: /opt/solrdata
SolrUser: solr
SolrPort: 8983
# the include file is: /etc/default/solr.in.sh
SolrInclude: solr
DownFrom: http://mirrors.hust.edu.cn/apache/lucene/solr/6.1.0/solr-6.1.0.tgz
Ini:
  ZK_HOST: nn.intranet.fh.gov.cn:2181,dn1.intranet.fh.gov.cn:2181,dn2.intranet.fh.gov.cn:2181,dn3.intranet.fh.gov.cn:2181,snn.intranet.fh.gov.cn:2181/solr
#SOLR_OPTS="$SOLR_OPTS -Dsolr.autoSoftCommit.maxTime=3000"
solrOptions:
  - -Dsolr.directoryFactory=solr.HdfsDirectoryFactory
  - -Dsolr.lock.type=hdfs
  - -Dsolr.hdfs.home=hdfs://nn.intranet.fh.gov.cn/solr
# need ./bin/hdfs dfs -mkdir /solr, ./bin/hdfs dfs -chown solr:solr /solr
enableSSL: true
sslOptions:
  ini:
    SOLR_SSL_KEY_STORE: /etc/solr-ssl.keystore.jks
    SOLR_SSL_KEY_STORE_PASSWORD: secret
    SOLR_SSL_TRUST_STORE: /etc/solr-ssl.keystore.jks
    SOLR_SSL_TRUST_STORE_PASSWORD: secret
    # Require clients to authenticate
    SOLR_SSL_NEED_CLIENT_AUTH: false
    # Enable clients to authenticate (but not require)
    SOLR_SSL_WANT_CLIENT_AUTH: false
  dname: "CN=solrcloud, OU=fhgov, O=xxzx, L=fenghua, ST=zj, C=cn"
solrNodes:
  - che.intranet.fh.gov.cn,10.74.111.70
  - nn.intranet.fh.gov.cn,10.74.111.62
